var e = require("./urlconstant"), s = "https://mina.xfliusheng.com/" == e.basequeryUrl || !1, r = {
    login: e.basequeryUrl + "user/authlogin",
    userinfo: e.basequeryUrl + "user/update",
    ttsurl: e.basequeryUrl + "synth/ttssynth",
    authtimes: e.basequeryUrl + "uservoice/authtime",
    strivetimes: e.basequeryUrl + "voice/nowstrivetime",
    timesstrive: e.basequeryUrl + "voice/strive",
    getresid: e.basequeryUrl + "voice/resourceid",
    getsamples: e.basequeryUrl + "voice/samplelist",
    materialupload: e.basequeryUrl + "voice/uploadmaterial",
    audioupload: e.basequeryUrl + "upload/audio",
    materialcheck: e.basequeryUrl + "voice/checkmaterial",
    voicetrainsubmit: e.basequeryUrl + "voice/starttrain",
    bindinvitecode: e.basequeryUrl + "uservoice/bindinvitationcode",
    validcode: e.basequeryUrl + "user/sendmobilecode",
    news: e.basequeryUrl + "news/list",
    tidbits: e.basequeryUrl + "worldcup/list",
    bindphone: e.basequeryUrl + "user/bindmobile",
    wxautobindmobile: e.basequeryUrl + "user/autobindmobile",
    uploadshare: e.basequeryUrl + "share/upload",
    sharedetail: e.basequeryUrl + "share/sharedetail",
    shareidget: e.basequeryUrl + "share/shareid",
    shareaction: e.basequeryUrl + "action/useraction",
    worldarticle: e.basequeryUrl + "article/detail",
    comment: e.basequeryUrl + "personal/comment",
    uploadPicture: e.basequeryUrl + "upload/img",
    uservoice: e.basequeryUrl + "uservoice/list",
    usrvoice: e.basequeryUrl + "uservoice/enablelist",
    ttssynth: e.basequeryUrl + "synth/ttssynth",
    listenhistorydetail: e.basequeryUrl + "listenhistory/detail",
    listenhistory: e.basequeryUrl + "listenhistory/list",
    listenhistorymanager: e.basequeryUrl + "listenhistory/manage",
    uservoicedelete: e.basequeryUrl + "uservoice/delete",
    textmodulelist: e.basequeryUrl + "textmodule/list",
    remindstrive: e.basequeryUrl + "voice/striveremind",
    shareacode: e.basequeryUrl + "share/acode",
    traintext: e.basequeryUrl + "train/text",
    taskadd: e.basequeryUrl + "train/taskadd",
    audioadd: e.basequeryUrl + "train/audioadd",
    audiodetail: e.basequeryUrl + "train/audiodetail",
    taskstart: e.basequeryUrl + "train/taskstart",
    enablelist: e.basequeryUrl + "uservoice/enablelist",
    uservoicelist: e.basequeryUrl + "uservoice/list",
    modulelist: e.basequeryUrl + "textmodule/modules",
    moduleinfo: e.basequeryUrl + "textmodule/module",
    categoryarticles: e.basequeryUrl + "textmodule/modulearticle",
    voiceplayurl: e.basequeryUrl + "textmodule/voiceplay",
    sensitivecheck: e.basequeryUrl + "train/sensitivetextcheck",
    voiceupgrade: e.basequeryUrl + "uservoice/upgrade",
    voiceupdate: e.basequeryUrl + "uservoice/update",
    voicespeeddetail: e.basequeryUrl + "uservoice/speeddetail",
    imgupload: e.basequeryUrl + "uservoice/uploadimage",
    uploadspeed: e.basequeryUrl + "uservoice/uploadspeed",
    voiceuploadform: e.basequeryUrl + "uservoice/uploadform",
    voicespeed: e.basequeryUrl + "uservoice/speed",
    banners: e.basequeryUrl + "cfg/getBanners",
    uploadwxformid: e.basequeryUrl + "user/uploadWeChatForm",
    trainNumber: e.basequeryUrl + "cfg/getRandomIncrNum",
    callTexts: e.basequeryUrl + "cfg/callconfig",
    sysvcns: e.basequeryUrl + "cfg/sysvcns"
}, i = s ? {
    userinfokey: "xfls_usr_online",
    progresskey: "xfls_train_progressV1_2_1_online",
    progresserrkey: "xfls_train_progressV1_2_1_err_online",
    guideviewedkey: "xfls_guide_viewed_online",
    headerurlkey: "xfls_headerurl_online",
    nexttimestrived: "xfls_strived_online",
    systeminfo: "xfls_sysinfo_online",
    defaultvcnkey: "xfls_dftvcn_online",
    callguideKey: "xfls_callguide_online",
    indexguideKey: "xfls_indexguide_online",
    indextimesguideKey: "xfls_indextimesguide_online",
    appsguideKey: "xfls_appsguide_online",
    shareguideKey: "xfls_shareguide_online",
    columnguideKey: "xfls_columnguide_online"
} : {
    userinfokey: "xfls_usr_ossp",
    progresskey: "xfls_train_progressV1_2_1_ossp",
    progresserrkey: "xfls_train_progressV1_2_1_err_ossp",
    guideviewedkey: "xfls_guide_viewed_ossp",
    headerurlkey: "xfls_headerurl_ossp",
    nexttimestrived: "xfls_strived_ossp",
    systeminfo: "xfls_sysinfo_ossp",
    defaultvcnkey: "xfls_dftvcn_ossp",
    callguideKey: "xfls_callguide_ossp",
    indexguideKey: "xfls_indexguide_ossp",
    indextimesguideKey: "xfls_indextimesguide_ossp",
    appsguideKey: "xfls_appsguide_ossp",
    shareguideKey: "xfls_shareguide_ossp",
    columnguideKey: "xfls_columnguide_ossp"
};

module.exports = {
    ifc: r,
    lkey: i,
    dataCfg: {
        strivespace: 1,
        recordNumber: 10,
        validCodeCountDownMax: 120
    },
    //原小程序  wx6f7b3d8b5ca680fa
    appId: "J9Q7O4EL"
};